import subprocess
import re
from pathlib import Path
import time
try:
    import docker
    DOCKER_AVAILABLE = True
except ImportError:
    DOCKER_AVAILABLE = False

class DockerEngine:
    """
    Manages all Docker operations
    """

    def __init__(self):
        if DOCKER_AVAILABLE:
            try:
                self.client = docker.from_env()
                self.buildkit_enabled = True
            except:
                self.client = None
                self.buildkit_enabled = False
        else:
            self.client = None
            self.buildkit_enabled = False

    def generate_optimized_dockerfile(self, service_config):
        """Generate production-ready Dockerfile"""

        template = self.select_template(service_config)

        # Add optimizations based on framework
        optimizations = self.get_optimizations(service_config)

        dockerfile = f"""
# Auto-generated by AI Deploy - Optimized for {service_config['framework']}
# Stage 1: Builder
FROM {template.base_image} AS builder
WORKDIR /app

# Copy dependency files
{self.copy_dependency_files(service_config)}

# Install dependencies with caching
RUN {self.get_install_command(service_config)}

# Copy source
COPY . .

# Build if needed
{self.get_build_command(service_config)}

# Stage 2: Runtime
FROM {template.runtime_image}
WORKDIR /app

# Copy from builder
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules

# Security: Run as non-root
USER 1000

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
    CMD curl -f http://localhost:{service_config['port']}/health || exit 1

# Optimize for production
ENV NODE_ENV=production \\
    PYTHONUNBUFFERED=1

EXPOSE {service_config['port']}

{self.get_run_command(service_config)}
"""
        return dockerfile

    def select_template(self, service_config):
        """Select appropriate template based on framework"""
        framework = service_config.get('framework', 'python')

        templates = {
            'fastapi': {
                'base_image': 'python:3.9-slim',
                'runtime_image': 'python:3.9-slim',
                'install_cmd': 'pip install --no-cache-dir -r requirements.txt',
                'run_cmd': 'uvicorn main:app --host 0.0.0.0 --port 8000'
            },
            'flask': {
                'base_image': 'python:3.9-slim',
                'runtime_image': 'python:3.9-slim',
                'install_cmd': 'pip install --no-cache-dir -r requirements.txt',
                'run_cmd': 'python app.py'
            },
            'django': {
                'base_image': 'python:3.9-slim',
                'runtime_image': 'python:3.9-slim',
                'install_cmd': 'pip install --no-cache-dir -r requirements.txt',
                'run_cmd': 'python manage.py runserver 0.0.0.0:8000'
            },
            'react': {
                'base_image': 'node:16-alpine',
                'runtime_image': 'nginx:alpine',
                'install_cmd': 'npm ci',
                'run_cmd': 'nginx -g "daemon off;"'
            },
            'nextjs': {
                'base_image': 'node:16-alpine',
                'runtime_image': 'node:16-alpine',
                'install_cmd': 'npm ci',
                'run_cmd': 'npm start'
            }
        }

        return templates.get(framework, templates['fastapi'])

    def get_optimizations(self, service_config):
        """Get framework-specific optimizations"""
        optimizations = []

        if service_config['framework'] == 'python':
            optimizations.append('--no-cache-dir')
        elif service_config['framework'] in ['react', 'nextjs']:
            optimizations.append('--production')

        return optimizations

    def copy_dependency_files(self, service_config):
        """Get dependency file copy commands"""
        if service_config['framework'] in ['react', 'nextjs']:
            return "COPY package*.json ./"
        else:
            return "COPY requirements.txt ."

    def get_install_command(self, service_config):
        """Get dependency installation command"""
        template = self.select_template(service_config)
        return template['install_cmd']

    def get_build_command(self, service_config):
        """Get build command if needed"""
        if service_config['framework'] in ['react', 'nextjs']:
            return "RUN npm run build"
        return ""

    def get_run_command(self, service_config):
        """Get run command"""
        template = self.select_template(service_config)
        return f"CMD {template['run_cmd']}"

    def build_image(self, service_name, dockerfile_path, tag):
        """Build Docker image with progress bars"""

        # Use BuildKit for faster builds
        env = {'DOCKER_BUILDKIT': '1'} if self.buildkit_enabled else {}

        # Build with layers caching
        try:
            image, logs = self.client.images.build(
                path='.',
                dockerfile=dockerfile_path,
                tag=f"{tag}:latest",
                rm=True,
                forcerm=True,
                pull=True,
                buildargs=self.get_build_args(),
                cache_from=[f"{tag}:latest"],
                labels={
                    'ai-deploy': 'true',
                    'service': service_name,
                    'timestamp': str(time.time())
                }
            )

            return image
        except Exception as e:
            return f"[ERROR] Error building image: {str(e)}"

    def get_build_args(self):
        """Get build arguments"""
        return {}

    def create_compose_file(self, services):
        """Generate docker-compose.yml for local development"""

        compose = {
            'version': '3.8',
            'services': {},
            'networks': {
                'app-network': {
                    'driver': 'bridge'
                }
            },
            'volumes': {}
        }

        for service in services:
            compose['services'][service['name']] = {
                'build': service['build_path'],
                'ports': [f"{service['port']}:{service['port']}"],
                'environment': service.get('env_vars', {}),
                'networks': ['app-network'],
                'depends_on': service.get('dependencies', []),
                'restart': 'unless-stopped'
            }

            # Add volumes for development
            if service.get('dev_mode'):
                compose['services'][service['name']]['volumes'] = [
                    f"./{service['name']}:/app",
                    "/app/node_modules"  # Exclude node_modules
                ]

        return compose

    # Legacy methods for compatibility
    def build_image_legacy(self, project_path=".", image_name="myapp"):
        """Build Docker image"""
        try:
            cmd = f"docker build -t {image_name} ."
            result = subprocess.run(cmd, shell=True, cwd=project_path,
                                  capture_output=True, text=True)

            if result.returncode == 0:
                return f"[SUCCESS] Docker image '{image_name}' built successfully"
            else:
                return f"[ERROR] Failed to build Docker image:\n{result.stderr}"

        except Exception as e:
            return f"[ERROR] Error building Docker image: {str(e)}"

    def run_container(self, image_name="myapp", port=8000):
        """Run Docker container"""
        try:
            # Stop any existing container with the same name
            self.stop_container("myapp-container")

            cmd = f"docker run -d --name myapp-container -p {port}:{port} {image_name}"
            result = subprocess.run(cmd, shell=True, capture_output=True, text=True)

            if result.returncode == 0:
                container_id = result.stdout.strip()
                return f"[SUCCESS] Container started: {container_id[:12]}"
            else:
                return f"[ERROR] Failed to start container:\n{result.stderr}"

        except Exception as e:
            return f"[ERROR] Error starting container: {str(e)}"

    def detect_port(self, project_info):
        """Detect the appropriate port based on framework"""
        framework = project_info.get("framework", "Unknown")

        port_map = {
            "FastAPI": 8000,
            "Flask": 5000,
            "Django": 8000,
            "Streamlit": 8501,
            "Node.js": 3000,
        }

        return port_map.get(framework, 8000)

    def get_container_status(self, container_name="myapp-container"):
        """Get container status"""
        try:
            cmd = f"docker ps -f name={container_name} --format '{{{{.Names}}}}:{{{{.Status}}}}:{{{{.Ports}}}}'"
            result = subprocess.run(cmd, shell=True, capture_output=True, text=True)

            if result.returncode == 0 and result.stdout.strip():
                return result.stdout.strip()
            else:
                return "No running containers found"

        except Exception as e:
            return f"Error checking container status: {str(e)}"

    def stop_container(self, container_name="myapp-container"):
        """Stop and remove container"""
        try:
            # Stop container
            cmd = f"docker stop {container_name}"
            subprocess.run(cmd, shell=True, capture_output=True)

            # Remove container
            cmd = f"docker rm {container_name}"
            subprocess.run(cmd, shell=True, capture_output=True)

            return f"[SUCCESS] Container '{container_name}' stopped and removed"

        except Exception as e:
            return f"[ERROR] Error stopping container: {str(e)}"

    def remove_image(self, image_name="myapp"):
        """Remove Docker image"""
        try:
            cmd = f"docker rmi {image_name}"
            result = subprocess.run(cmd, shell=True, capture_output=True, text=True)

            if result.returncode == 0:
                return f"[SUCCESS] Image '{image_name}' removed"
            else:
                return f"[ERROR] Failed to remove image: {result.stderr}"

        except Exception as e:
            return f"[ERROR] Error removing image: {str(e)}"

    def push_image(self, image_name="myapp", registry=""):
        """Push image to registry"""
        try:
            full_image_name = f"{registry}/{image_name}" if registry else image_name
            cmd = f"docker push {full_image_name}"
            result = subprocess.run(cmd, shell=True, capture_output=True, text=True)

            if result.returncode == 0:
                return f"[SUCCESS] Image pushed to registry: {full_image_name}"
            else:
                return f"[ERROR] Failed to push image:\n{result.stderr}"

        except Exception as e:
            return f"[ERROR] Error pushing image: {str(e)}"